### ISSUE TITLE
integration

### ISSUE THREAD

**Issue by suzuki-hoge** [suzuki-hoge/has-hub#20]
+ [ ] ~~integrate fixme failures~~ -> fixed #39 
+ [ ] ~~create object from yaml objects~~ -> fixed #21 
+ [x] validate all and create or show fix-me
+ [ ] ~~parameter to local-session~~ -> will fix #11 
+ [x] milestone-title and referred milestones mapping
+ [x] pipeline-name and referred pipelines mapping
+ [x] epic-link-number and allocated epic-number mapping
+ [x] show progress message

**Comment by suzuki-hoge** [comment]
6a9135a0dcf28146d1f8749b4f1bcd015e5ff5e8
